### PR TITLE
fix(navbar): make navbar responsive on mobile

### LINKED ISSUE #4: Fix navbar sizing issues on mobile
Implement a button and drawer system for mobile

### PR DESCRIPTION
**Pull request by akshada-31**
#4

### CODE REVIEW

File: src/components/Navbar.jsx [hunk 1]
```diff
@@ -1,54 +1,96 @@
...
+              viewBox="0 0 24 24"
+              stroke="currentColor"
+              strokeWidth={2}
+            >
+              <path strokeLinecap="round" strokeLinejoin="round" d="M4 6h16M4 12h16M4 18h16" />
+            </svg>
+          )}
+        </button>
+        {/* Optional title or logo */}
+        <div className="text-black font-semibold">Menu</div>
```
Comment (nikinmaheshkumar) [inline src/components/Navbar.jsx]: Remove the text menu

File: src/components/Navbar.jsx [hunk 2]
```diff
@@ -1,54 +1,96 @@
...
-        </ul>
-
-        {/* Mobile Menu */}
-        <div className="dropdown md:hidden">
-          <div tabIndex={0} role="button" className="btn btn-ghost">
-            ☰
-          </div>
-          <ul
-            tabIndex={0}
-            className="menu menu-sm dropdown-content mt-3 p-2 shadow bg-base-100 rounded-box w-52"
```
Comment (nikinmaheshkumar) [inline src/components/Navbar.jsx:42]: Design the elements in mobile better

**Review by nikinmaheshkumar — CHANGES_REQUESTED** [review]
Complete this by 12

**Comment by akshada-31** [comment]
I have removed the text "Menu" in fix/navbar and for the enhanced design for mobile i've committed the changes in feat/homepage.

File: src/components/Navbar.jsx (hunk 2 above)
Comment (nikinmaheshkumar) [reply src/components/Navbar.jsx:42]: Make the background color match the general theme of the site, try transparency if you can. Also design the elements in a better way.

**Review by nikinmaheshkumar — CHANGES_REQUESTED** [review]

**Comment by akshada-31** [comment]
Made the background transparent, the change in design of elements have already been made in the separate  homepage branch to avoid conflict issues.

**Review by nikinmaheshkumar — APPROVED** [review]
